apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service-deployment
spec:
  replicas: 2                             # Number of pods
  selector:                               #
    matchLabels:                          # This selector MUST MATCH below labels
      app: node-deployment-label          #

  # Pod template
  template:
    metadata:
      labels:
        app: node-deployment-label
    spec:
      containers:
        - name: demo-node-service
          image: thanh1669/demo-node-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: VERSION
              value: "1.0.0"
            - name: MONGODB_URI
              value: "mongodb://mongodb-svc:27017/test-db"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
