---
apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  type: NodePort                       # Chỉ tạo Virtual IP
  selector:
    app: node-deployment-label         # Label selector
  ports:
    - protocol: TCP                    # Protocol
      targetPort: 3000                 # Port của container
      port: 80                         # Port của service
      nodePort: 30008                  # Port của host

# Service trong cluster sẽ gọi         http://node-svc
# Request bên ngoài cluster gọi        http://<ip-host>:30008